export const theme = {
  colors: {
    surface: '#f9f9f9',
    surfaceDim: '#dadada',
    surfaceBright: '#f9f9f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f3f3',
    surfaceContainer: '#eeeeee',
    surfaceContainerHigh: '#e8e8e8',
    surfaceContainerHighest: '#e2e2e2',
    onSurface: '#1b1b1b',
    onSurfaceVariant: '#434655',
    inverseSurface: '#303030',
    inverseOnSurface: '#f1f1f1',
    outline: '#737686',
    outlineVariant: '#c3c6d7',
    surfaceTint: '#0053db',
    primary: '#004ac6',
    onPrimary: '#ffffff',
    primaryContainer: '#2563eb',
    onPrimaryContainer: '#eeefff',
    inversePrimary: '#b4c5ff',
    secondary: '#5f5e5e',
    onSecondary: '#ffffff',
    secondaryContainer: '#e4e2e1',
    onSecondaryContainer: '#656464',
    tertiary: '#943700',
    onTertiary: '#ffffff',
    tertiaryContainer: '#bc4800',
    onTertiaryContainer: '#ffede6',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#dbe1ff',
    primaryFixedDim: '#b4c5ff',
    onPrimaryFixed: '#00174b',
    onPrimaryFixedVariant: '#003ea8',
    secondaryFixed: '#e4e2e1',
    secondaryFixedDim: '#c8c6c6',
    onSecondaryFixed: '#1b1c1c',
    onSecondaryFixedVariant: '#474747',
    tertiaryFixed: '#ffdbcd',
    tertiaryFixedDim: '#ffb596',
    onTertiaryFixed: '#360f00',
    onTertiaryFixedVariant: '#7d2d00',
    background: '#f9f9f9',
    onBackground: '#1b1b1b',
    surfaceVariant: '#e2e2e2',
  },
  typography: {
    displayXl: {
      fontFamily: 'Inter',
      fontSize: 40,
      fontWeight: '900',
      lineHeight: 48,
      letterSpacing: -1,
    },
    headlineLg: {
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: '800',
      lineHeight: 32,
      letterSpacing: -0.5,
    },
    headlineMd: {
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: '800',
      lineHeight: 28,
      letterSpacing: -0.5,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 24,
      letterSpacing: 0,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0,
    },
    labelSm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
      letterSpacing: 1,
    },
  },
  spacing: {
    unit: 4,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 48,
    marginMobile: 20,
    gutter: 16,
  },
  rounded: {
    sm: 2,
    default: 4,
    md: 6,
    lg: 8,
    xl: 12,
    full: 9999,
  },
};

export default theme;
